from typing import Any, Dict, List
from memory.knowledge_graph import KnowledgeGraphService
from memory.policy_engine import PolicyEngineService
from memory.failure_repository import FailureRepository

class MemoryUpdater:
    """Applies updates generated by the learning engine back to the shared core services."""

    def apply_updates(
        self,
        updates: List[Dict[str, Any]],
        knowledge_graph: KnowledgeGraphService,
        policy_engine: PolicyEngineService,
        failure_repo: FailureRepository
    ) -> None:
        """Executes each update action against the appropriate service."""
        for update in updates:
            action = update.get("action")
            if action == "LOG_FAILURE":
                failure_repo.log_failure(
                    run_id=update["run_id"],
                    component=update["component"],
                    error_message=update["error_message"]
                )
            elif action == "ADD_TRIPLE":
                knowledge_graph.add_triple(
                    subject=update["subject"],
                    predicate=update["predicate"],
                    obj=update["obj"],
                    metadata=update.get("metadata")
                )
            # Other actions (e.g. POLICY_UPDATE) could be added here in compliance with OCP
