from typing import Any, Dict, List, Optional
from memory.knowledge_graph import KnowledgeGraphService
from memory.policy_engine import PolicyEngineService
from memory.failure_repository import FailureRepository
from memory.evidence_store import EvidenceStoreService

class MemoryUpdater:
    """Applies updates generated by the learning engine back to the shared core services."""

    def apply_updates(
        self,
        updates: List[Dict[str, Any]],
        knowledge_graph: KnowledgeGraphService,
        policy_engine: PolicyEngineService,
        failure_repo: FailureRepository,
        evidence_store: Optional[EvidenceStoreService] = None
    ) -> None:
        """Executes each update action against the appropriate service."""
        for update in updates:
            action = update.get("action")
            if action == "LOG_FAILURE":
                failure_repo.log_failure(
                    run_id=update["run_id"],
                    component=update["component"],
                    error_message=update["error_message"]
                )
            elif action == "ADD_TRIPLE":
                knowledge_graph.add_triple(
                    subject=update["subject"],
                    predicate=update["predicate"],
                    obj=update["obj"],
                    metadata=update.get("metadata")
                )
            elif action == "STORE_EVIDENCE" and evidence_store is not None:
                evidence_store.store_evidence(
                    run_id=update["run_id"],
                    evidence_type=update.get("evidence_type", "learning_update"),
                    content=update.get("content", update),
                    metadata=update.get("metadata")
                )

