from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

class Domain(Enum):
    SPECIFICATION = "SPECIFICATION"
    RESEARCH = "RESEARCH"
    ARCHITECTURE = "ARCHITECTURE"
    ENGINEERING = "ENGINEERING"
    EVALUATION = "EVALUATION"
    DEPLOYMENT = "DEPLOYMENT"
    LEARNING = "LEARNING"

@dataclass
class Intent:
    """Represents the analyzed engineering intent from the user request."""
    request_text: str
    intent_type: str
    required_domains: List[Domain]
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class ExecutionContext:
    """Contains active session context, project state, policy constraints, and knowledge graph facts."""
    run_id: str
    variables: Dict[str, Any] = field(default_factory=dict)
    state: Dict[str, Any] = field(default_factory=dict)
    policies: List[Dict[str, Any]] = field(default_factory=list)
    knowledge_triples: List[Any] = field(default_factory=list)

@dataclass
class ExecutionStep:
    """A single step in the execution plan."""
    step_id: str
    domain: Domain
    parameters: Dict[str, Any] = field(default_factory=dict)

@dataclass
class ExecutionPlan:
    """A sequence of steps (execution strategy) to resolve the request."""
    run_id: str
    steps: List[ExecutionStep] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)

@dataclass
class HarnessResult:
    """Outcome of a single Harness execution."""
    success: bool
    outputs: Dict[str, Any] = field(default_factory=dict)
    logs: List[str] = field(default_factory=list)
    error_message: Optional[str] = None
    updated_variables: Dict[str, Any] = field(default_factory=dict)
    updated_state: Dict[str, Any] = field(default_factory=dict)

@dataclass
class ExecutionArtifacts:
    """Consolidated outputs and artifacts generated by the orchestrator run."""
    run_id: str
    success: bool
    generated_files: Dict[str, str] = field(default_factory=dict)  # filepath -> content
    test_results: Dict[str, Any] = field(default_factory=dict)
    deployment_status: Optional[str] = None
    harness_results: List[HarnessResult] = field(default_factory=list)
